steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.anomaly_detection'
      - '-t'
      - 'us-west2-docker.pkg.dev/$PROJECT_ID/anomaly/anomaly-daemon:v0.4.6'
      - '-t'
      - 'us-west2-docker.pkg.dev/$PROJECT_ID/anomaly/anomaly-daemon:latest'
      - '.'
images:
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/anomaly/anomaly-daemon:v0.4.6'
  - 'us-west2-docker.pkg.dev/$PROJECT_ID/anomaly/anomaly-daemon:latest'
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
